name: Environment GITHUB_TOKEN
on: push
env:
  workflow_env: ${{secrets.GITHUB_TOKEN}}#Available to all jobs
jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Push a random file
        run: |
          pwd
          ls
          git init
          git remote add origin "https://$github.actor:${{secrets.GITHUB_TOKEN}}@github.com/$github.repository.git"
          git config --global user.email "likhithayeturi06@gmail.com"
          git config --global user.name "likhithayeturi06"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull
          ls
          echo $RANDOM >> random.txt
          ls
          git add .
          git commit -m "Random File"
          git push
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{github.repository}}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail